[package]
name = "loop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
loop_lib = { path = "../loop_lib" }
rayon = "1.7"
walkdir = "2.3"
serde_json = "1.0"

[[bin]]
name = "loop"
path = "src/main.rs"
